import { describe, it, expect } from 'vitest'
import { readFileSync, readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

// Guards the Task 7 vacuous-pass regression.
//
// `CheckRunner.parseFrontmatter` is a line-regex scalar parser: it cannot
// represent the nested `checks` list, so feeding its output to
// `UIControls.bind` made `runChecks` iterate a string (or nothing at all) and
// report PASS for every submission. The page must take its lesson metadata
// from the manifest entry, where `build-manifest` has already parsed the YAML.
//
// These are source-text assertions on purpose: reproducing the regression in a
// browser is the job of the real-device test, not of vitest.

// jsdom's `URL` cannot resolve a relative path against a `file:` base, so
// build the paths from this file's own directory.
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const html = readFileSync(path.join(repoRoot, 'site/index.html'), 'utf8')
const manifest = JSON.parse(readFileSync(path.join(repoRoot, 'content/manifest.json'), 'utf8'))

/**
 * The page's wiring lives in its module script; scope assertions to it and
 * drop full-line comments, so commented-out code cannot trip a source check.
 */
function moduleScript() {
  const m = html.match(/<script type="module">([\s\S]*?)<\/script>/)
  if (!m) throw new Error('site/index.html has no <script type="module"> block')
  return m[1]
    .split('\n')
    .filter((line) => !/^\s*\/\//.test(line))
    .join('\n')
}

describe('index.html takes lesson metadata from the manifest', () => {
  it('awaits LiaScriptLoader.getLesson for the lesson object', () => {
    expect(moduleScript()).toMatch(
      /const\s+lesson\s*=\s*await\s+window\.LiaScriptLoader\.getLesson\(/,
    )
  })

  it('binds parseFrontmatter to the Markdown body only', () => {
    const script = moduleScript()
    const destructure = script.match(/(?:const|let|var)\s*\{([^}]*)\}\s*=\s*[^\n]*parseFrontmatter\(/)
    expect(destructure).not.toBeNull()
    expect(destructure[1]).toMatch(/\bbody\b/)
    // Destructuring `meta` anywhere in the wiring is the regression: that
    // object is scalar-only. Matched as a binding, and only inside the module
    // script, so a comment cannot trip it.
    expect(script).not.toMatch(/(?:const|let|var)\s*\{[^}]*\bmeta\b[^}]*\}\s*=/)
  })
})

describe('site/ reaches every runtime asset by a document-relative URL', () => {
  // GitHub Pages serves this as a PROJECT site at
  // https://<user>.github.io/python/, so a leading slash resolves to the domain
  // root and 404s every asset — the deployed page renders a header and
  // "Loading lesson…" and nothing else. Serving site/ on localhost is the one
  // layout where absolute paths happen to work, which is why this went unseen:
  // scan the sources instead.
  const ABSOLUTE_ASSET_URL = /["']\/(?:assets|content)\//

  function siteSources(dir) {
    return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
      const full = path.join(dir, entry.name)
      if (entry.isDirectory()) return siteSources(full)
      if (!/\.(?:html|js)$/.test(entry.name)) return []
      // Generated by esbuild; it inlines no such URL and is not hand-edited.
      if (entry.name === 'code-editor.bundle.js') return []
      return [full]
    })
  }

  it('has no leading-slash /assets/ or /content/ reference', () => {
    const offenders = siteSources(path.join(repoRoot, 'site'))
      .filter((file) => ABSOLUTE_ASSET_URL.test(readFileSync(file, 'utf8')))
      .map((file) => path.relative(repoRoot, file))
    expect(offenders).toEqual([])
  })
})

describe('index.html passes an array of checks into UIControls.bind', () => {
  it('hands the manifest entry to UIControls.bind', () => {
    // Whitespace-tolerant: the payload may be reformatted onto one line.
    const bindCall = moduleScript().match(/window\.UIControls\.bind\(\s*\{([\s\S]*?)\}\s*\)/)
    expect(bindCall).not.toBeNull()
    expect(bindCall[1]).toMatch(/lesson\s*:\s*lesson\b/)
  })

  it('that entry carries checks as an array of check objects', () => {
    const defaultId = html.match(/params\.get\('id'\)\s*\|\|\s*'([^']+)'/)?.[1]
    expect(defaultId).toBeTruthy()
    const entry = manifest.lessons.find((lesson) => lesson.id === defaultId)
    expect(entry).toBeDefined()
    expect(Array.isArray(entry.checks)).toBe(true)
    expect(entry.checks.length).toBeGreaterThan(0)
    for (const check of entry.checks) {
      expect(typeof check.kind).toBe('string')
    }
  })
})
